In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv(r'C:\Users\Welcome\Stay_of_patient.csv')
dataset

date location  age        disease sevearity_of_the_disease  \
0    06-04-2012    India   42    heartstroke                     high   
1    07-05-2012    India   41         cancer                      low   
2    09-01-2012    India   42    heartstroke                 moderate   
3    05-11-2012    India   39         cancer                      low   
4    06-04-2012    India   43         cancer                      low   
5    07-05-2012    India   44  bone fracture                     high   
6    09-01-2012    India   50  bone fracture                 moderate   
7    05-11-2012    India   29          fever                     high   
8    09-01-2012    India   44          fever                     high   
9    09-01-2012    India   27    heartstroke                 moderate   
10   09-01-2012    India   31         cancer                     high   
11   09-01-2012    India   24  bone fracture                      low   
12   09-01-2012    India   34    heartstroke                 moderate   
13   09-01-2012    India   25         cancer                 moderate   
14   09-01-2012    India    8          fever                      low   
15   06-04-2012    India   45          fever                     high   
16   06-04-2012    India   58         cancer                 moderate   
17   06-04-2012    India   24         cancer                      low   
18   06-04-2012    India   45  bone fracture                     high   
19   06-04-2012    India   24  bone fracture                      low   
20   06-04-2012    India   41         cancer                 moderate   
21   06-04-2012    India   32          astma                      low   
22   06-04-2012    India   38         cancer                      low   
23   06-04-2012    India   46         cancer                     high   
24   06-04-2012    India   38  bone fracture                 moderate   
25   06-04-2012    India   25  bone fracture                     high   
26    8/29/2012    India   36          fever                     high   
27    5/26/2012    India   44          fever                 moderate   
28    9/22/2012    India   43          fever                     high   
29   08-09-2012    India   29    heartstroke                      low   
..          ...      ...  ...            ...                      ...   
469   3/26/2012    India    8          fever                     high   
470  08-07-2012    India   27    heartstroke                 moderate   
471  12-02-2012    India   37         cancer                      low   
472   2/27/2012    India   26  bone fracture                      low   
473   6/20/2012    India   28    heartstroke                     high   
474   9/18/2012    India   33         cancer                 moderate   
475  08-05-2012    India   46          fever                     high   
476  12/18/2012    India   31          fever                     high   
477  09-02-2012    India   40         cancer                 moderate   
478   9/28/2012    India   38         cancer                     high   
479  07-03-2012    India   29  bone fracture                      low   
480  11-11-2012    India   34  bone fracture                 moderate   
481   9/25/2012    India   23         cancer                 moderate   
482  09-01-2012    India   37          astma                      low   
483  11/18/2012    India   37         cancer                     high   
484   7/18/2012    India   61         cancer                 moderate   
485   5/16/2012    India    8  bone fracture                      low   
486  11/19/2012    India   37  bone fracture                     high   
487  12/26/2012    India   39          fever                      low   
488  11-02-2012    India   30          fever                 moderate   
489  02-05-2012    India   55          fever                      low   
490  02-05-2012    India   29    heartstroke                      low   
491  02-05-2012    India   41         cancer                     high

In [3]:
import os
os.getcwd()

'C:\\Anaconda3\\Scripts'

In [4]:
dataset.isnull().any()

date                        False
location                    False
age                         False
disease                     False
sevearity_of_the_disease    False
frequency_of_suffering      False
pulse                       False
duration_of_suffering       False
length_of_stay              False
dtype: bool

In [5]:
x = dataset.iloc[:, 2:8].values
y = dataset.iloc[:, 8].values

In [6]:
x

array([[42, 'heartstroke', 'high', 'regural', 96, 6],
       [41, 'cancer', 'low', 'irregular', 61, 2],
       [42, 'heartstroke', 'moderate', 'irregular', 64, 4],
       ...,
       [32, 'bone fracture', 'high', 'regular', 68, 6],
       [40, 'fever', 'low', 'irregular', 61, 2],
       [26, 'fever', 'moderate', 'irregular', 70, 6]], dtype=object)

In [7]:
y

array([ 3,  2,  1,  5,  2,  7,  3,  3, 10,  2,  8,  3,  6,  9,  6, 30,  7,
       10,  4, 11, 14, 12,  4,  9,  6, 12, 11,  2,  1,  5,  2, 15,  3,  3,
       10,  2,  8,  3,  6,  9,  6, 30,  7, 10,  4, 11, 14, 12,  4,  9,  6,
       12, 11,  2,  1,  5,  2, 15,  3,  3, 10,  2,  1,  5,  2, 15,  3,  3,
       10,  2,  8,  3,  6,  9,  6, 30,  7, 10,  4, 11, 14, 12,  4,  9,  6,
       12, 11,  2,  1,  5,  2, 15,  3,  3, 10,  2,  8,  3,  6,  9,  6, 30,
        7, 10,  4, 11, 14, 12,  4,  9,  6, 12, 11,  2,  1,  5,  2, 15,  3,
        3, 10,  2,  1,  5,  2, 15,  3,  3, 10,  2,  8,  3,  6,  9,  6, 30,
        7, 10,  4, 11, 14, 12,  4,  9,  6, 12, 11,  2,  1,  5,  2, 15,  3,
        3, 10,  2,  8,  3,  6,  9,  6, 30,  7, 10,  4, 11, 14, 12,  4,  9,
        6, 12, 11,  2,  1,  5,  2, 15,  3,  3, 10,  2,  1,  5,  2, 15,  3,
        3, 10,  2,  8,  3,  6,  9,  6, 30,  7, 10,  4, 11, 14, 12,  4,  9,
        6, 12, 11,  2,  1,  5,  2, 15,  3,  3, 10,  2,  8,  3,  6,  9,  6,
       30,  7, 10,  4, 11

In [8]:
from sklearn.preprocessing import LabelEncoder

#Label Encoding

labelencoder_X = LabelEncoder()
x[:, 1] = labelencoder_X.fit_transform(x[:,1])
labelencoder_X2 = LabelEncoder()
x[:, 2] = labelencoder_X2.fit_transform(x[:,2])
labelencoder_X3 = LabelEncoder()
x[:, 3] = labelencoder_X3.fit_transform(x[:,3])


In [9]:
x

array([[42, 4, 0, 2, 96, 6],
       [41, 2, 1, 0, 61, 2],
       [42, 4, 2, 0, 64, 4],
       ...,
       [32, 1, 0, 1, 68, 6],
       [40, 3, 1, 0, 61, 2],
       [26, 3, 2, 0, 70, 6]], dtype=object)

In [29]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [1])
x = onehotencoder.fit_transform(x).toarray()
x=x[:,1:]

C:\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:385: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [66]:
x.reshape

<function ndarray.reshape>

In [49]:
onehotencoder = OneHotEncoder(categorical_features = [6])
x = onehotencoder.fit_transform(x).toarray()
x=x[:,1:]

C:\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:385: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [50]:
x

array([[ 0.,  0.,  0., ...,  0., 96.,  6.],
       [ 0.,  0.,  0., ...,  1., 61.,  2.],
       [ 0.,  0.,  0., ...,  2., 64.,  4.],
       ...,
       [ 0.,  0.,  0., ...,  0., 68.,  6.],
       [ 0.,  0.,  0., ...,  1., 61.,  2.],
       [ 0.,  0.,  0., ...,  2., 70.,  6.]])

In [51]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [52]:
x_train

array([[ 0.,  0.,  0., ...,  1., 64.,  2.],
       [ 0.,  0.,  0., ...,  1., 77.,  2.],
       [ 0.,  0.,  0., ...,  1., 88.,  2.],
       ...,
       [ 0.,  0.,  0., ...,  0., 71.,  6.],
       [ 0.,  0.,  0., ...,  1., 73.,  2.],
       [ 0.,  0.,  0., ...,  1., 95.,  2.]])

In [53]:
y_train

array([12,  3,  3, 11,  3,  6,  2,  2,  3,  2, 15,  3, 10, 10,  2, 30,  3,
       10,  2, 10, 10,  9,  6,  5,  8,  3,  3,  4,  5,  9,  1,  9,  2,  5,
       11,  3,  8,  2,  2,  3,  6, 11,  6, 11, 15,  2, 10,  5,  2,  7, 12,
       12, 30,  8,  1,  4, 10, 14,  9,  6,  3, 11,  2, 11, 12, 12,  1,  2,
        7,  9,  3,  6,  2,  1,  9, 11,  4, 12, 15,  2,  2,  4, 14,  3,  5,
        7, 15, 10, 11,  5,  3,  5,  3, 15,  3,  3,  3,  3,  4,  4, 12,  6,
        2, 15, 12,  6,  6, 10,  3, 10,  6, 14, 30,  3,  1, 14, 10, 11, 10,
        4,  2,  1,  3, 10, 12,  2,  2, 15,  2,  4,  2, 10, 14, 11,  2,  3,
       30,  7,  8, 11,  2,  3,  6,  3, 11,  3, 11, 11,  9,  3,  1,  7, 10,
        4,  3, 12,  2, 11,  2,  6,  9,  2,  1,  5,  3,  9, 12,  3,  2,  6,
        4,  8, 12, 10,  4,  3,  4,  7,  4,  9,  2, 11,  2, 10,  6,  1,  4,
        3,  6,  8, 10,  2, 12, 14,  5,  3,  6,  3,  9, 11,  6,  6,  9, 14,
       12,  3,  4, 30,  9,  6,  2,  6,  5,  3,  7,  9,  9,  6, 11, 15, 11,
        2,  7,  6,  6,  3

In [54]:
from sklearn.linear_model import LinearRegression

In [55]:
mlr=LinearRegression()

In [56]:
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [57]:
y_pred = mlr.predict(x_test)

In [58]:
x_test

array([[ 0.,  0.,  0., ...,  0., 67.,  6.],
       [ 0.,  0.,  0., ...,  2., 96.,  4.],
       [ 0.,  0.,  0., ...,  2., 85.,  4.],
       ...,
       [ 0.,  0.,  0., ...,  0., 60.,  6.],
       [ 0.,  0.,  0., ...,  2., 66.,  4.],
       [ 0.,  0.,  0., ...,  0., 70.,  6.]])

In [59]:
y_pred

array([ 9.26423745e+00,  3.88249307e+00,  6.84285073e+00,  2.52625513e-01,
        3.72566323e+00,  7.00673013e+00,  9.76838784e+00,  9.01204019e+00,
        3.82905679e+00,  5.53218179e+00,  5.93440347e+00,  7.95723062e+00,
        3.47480874e+00,  9.76545815e+00,  6.33850194e+00,  8.54219155e+00,
        6.10615640e+00,  8.49000649e+00,  7.18519692e+00,  4.09809976e+00,
        8.20039468e+00,  3.24653726e+00,  6.20893960e+00,  5.34797769e+00,
        9.77839761e+00,  7.88081460e+00,  8.29304604e+00,  6.59199624e+00,
        8.10798745e+00, -4.91193966e+12, -1.70932368e+05,  8.43818765e+00,
        4.38884072e+00,  6.55952554e+00,  6.23347573e+00,  6.09260659e+00,
        1.15478068e+01,  6.89741616e+00,  1.01858683e+01,  6.99519448e+00,
        6.77131753e+00,  5.35974218e+00,  6.19403939e+00,  1.13329630e+01,
        4.12731461e+00,  8.17121987e+00,  8.43452554e+00,  8.04011636e+00,
        7.96626382e+00,  9.12764077e+00,  7.42656045e+00,  6.35786538e+00,
        1.17340188e+00,  

In [60]:
y_test

array([ 2,  9,  7,  9,  2, 30, 30,  3,  9,  3,  5,  2,  3,  4, 12,  2, 14,
        2, 10,  3, 12,  2, 10,  4, 11,  7, 12, 15,  8,  2, 11,  3,  2,  3,
       15, 15,  8,  6, 12,  3, 12, 14, 30, 30,  7,  2,  3,  6,  2,  7,  2,
        6, 30,  6,  6,  6, 11,  2,  4,  2,  4,  2, 12,  5, 10,  7,  8,  7,
        2, 30,  4, 15,  6, 15,  5, 10,  9,  6, 10,  1,  3,  5,  2,  9,  1,
       12,  9,  3, 14,  1,  6,  6, 10, 14,  3, 14,  2,  4, 10,  1],
      dtype=int64)

In [61]:
mlr.intercept_

4.657425927722921

In [62]:
x_train.shape

(399, 61)

In [63]:
mlr.coef_

array([ 4.46168643e+00,  7.64534502e+00, -4.91193966e+12, -3.70434503e+00,
        7.87480158e-01,  1.42846477e+00, -1.69482021e+00, -7.71141166e-01,
       -2.34211734e+00, -4.90115356e+00, -2.28881836e+00,  2.23095703e+00,
        4.04785156e-01,  1.63073730e+00, -3.64880371e+00,  4.99633789e-01,
        2.78076172e-01, -1.29541016e+00, -1.74829102e+00, -2.02709961e+00,
       -1.22399902e+00,  1.62231445e-01, -1.15246582e+00, -2.10479736e+00,
        8.12133789e-01, -2.04528809e-01, -2.48767090e+00, -6.94740295e+00,
        2.46656799e+00,  8.21166992e-01, -5.82427979e-01,  5.02097321e+00,
       -1.93128204e+00,  3.81107330e-01,  1.88475990e+00, -4.78426170e+00,
       -4.64205933e+00, -2.47077942e+00,  4.97718811e-01, -1.36393166e+00,
       -4.76746368e+00, -3.64714813e+00, -1.70940402e+05, -5.60693359e+00,
       -3.43276978e+00, -8.07182693e+00, -2.74894714e+00, -1.28577423e+00,
       -2.09308624e+00,  1.62200165e+00, -5.69067383e+00, -5.67120743e+00,
       -5.73534393e+00,  

In [64]:
from sklearn.metrics import r2_score

In [65]:
r2_score(y_test,y_pred)

-5.066057856750197e+21